# Site settings
title: "Chantal + Benjamin"
description: |
    Villa Boveri & Grand Casino, Baden

    05 Juli 2022
owner: Benjamin Huser
first_published: 2021
email: benj.huser@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.sabrinaevittoriosposi.it" # the base hostname & protocol for your site

# Google analytics
#google_analytics: "UA-40721189-2"

social:
  github: https://github.com/huserben/weddingpage

# Build settings
markdown: kramdown
